# Generated by Django 3.1.7 on 2021-04-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_activo', models.IntegerField()),
                ('desc_activo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ambiente', models.IntegerField()),
                ('desc_ambiente', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comentario', models.IntegerField()),
                ('id_inc', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('ts_comentario', models.DateField()),
                ('mensaje', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='criticidadservicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_criticidad_servicio', models.IntegerField()),
                ('desc_critividad_servicio', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_documento', models.IntegerField()),
                ('id_inc', models.IntegerField()),
                ('titulo_docu', models.CharField(max_length=45)),
                ('desc_origen', models.CharField(max_length=200)),
                ('ruta_documento', models.CharField(max_length=100)),
                ('ts_documento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estado', models.IntegerField()),
                ('desc_estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_etapa', models.IntegerField()),
                ('desc_oetapa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='impacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_impacto', models.IntegerField()),
                ('desc_impacto', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_origen', models.IntegerField()),
                ('desc_origen', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_servicio', models.IntegerField()),
                ('desc_servicio', models.CharField(max_length=45)),
                ('id_criticidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='severidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_severidad', models.IntegerField()),
                ('desc_severidad', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='tipoincidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo', models.IntegerField()),
                ('desc_tipo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ubicacion', models.IntegerField()),
                ('desc_ubicacion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='urgencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_urgencia', models.IntegerField()),
                ('desc_urgencia', models.CharField(max_length=45)),
            ],
        ),
    ]
