# Generated by Django 3.1.7 on 2021-04-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activos',
            fields=[
                ('id_activo', models.AutoField(primary_key=True, serialize=False)),
                ('desc_activo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'activos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id_ambiente', models.AutoField(primary_key=True, serialize=False)),
                ('desc_ambiente', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ambientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('ts_comentario', models.DateTimeField()),
                ('mensaje', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'comentarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Criticidadesservicios',
            fields=[
                ('id_criticidad_serv', models.AutoField(primary_key=True, serialize=False)),
                ('desc_criticidad_serv', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'criticidadesservicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallesambientes',
            fields=[
                ('id_detalle_ambiente', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detallesambientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallesservicios',
            fields=[
                ('id_detalle_servicio', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detallesservicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallesubicacion',
            fields=[
                ('id_detalle_ubicacion', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detallesubicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_doc', models.CharField(max_length=45)),
                ('desc_documento', models.CharField(max_length=200)),
                ('ruta_documento', models.CharField(max_length=100)),
                ('ts_documento', models.DateTimeField()),
            ],
            options={
                'db_table': 'documentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('desc_estado', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('desc_etapa', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'etapas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Impactos',
            fields=[
                ('id_impacto', models.AutoField(primary_key=True, serialize=False)),
                ('desc_impacto', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'impactos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidentes',
            fields=[
                ('id_inc', models.AutoField(primary_key=True, serialize=False)),
                ('desc_inc', models.CharField(max_length=200)),
                ('cli_afectados', models.IntegerField()),
                ('prov_involucrado', models.IntegerField()),
                ('act_afectados', models.IntegerField()),
                ('cont_comentarios', models.IntegerField()),
                ('cont_documentos', models.IntegerField()),
                ('ts_inc', models.DateTimeField()),
                ('ts_cierre', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incidentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Origenes',
            fields=[
                ('id_origen', models.AutoField(primary_key=True, serialize=False)),
                ('desc_origen', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'origenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('desc_servicio', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Severidades',
            fields=[
                ('id_severidad', models.AutoField(primary_key=True, serialize=False)),
                ('desc_severidad', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'severidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposincidentes',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tiposincidentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('desc_ubicacion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ubicaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Urgencias',
            fields=[
                ('id_urgencia', models.AutoField(primary_key=True, serialize=False)),
                ('desc_urgencia', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'urgencias',
                'managed': False,
            },
        ),
    ]
