# Generated by Django 3.1.7 on 2021-04-09 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0002_activos_ambientes_comentarios_criticidadesservicios_detallesambientes_detallesservicios_detallesubic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='activo',
        ),
        migrations.DeleteModel(
            name='ambiente',
        ),
        migrations.DeleteModel(
            name='comentario',
        ),
        migrations.DeleteModel(
            name='criticidadservicio',
        ),
        migrations.DeleteModel(
            name='documento',
        ),
        migrations.DeleteModel(
            name='estado',
        ),
        migrations.DeleteModel(
            name='etapa',
        ),
        migrations.DeleteModel(
            name='impacto',
        ),
        migrations.DeleteModel(
            name='origen',
        ),
        migrations.DeleteModel(
            name='servicio',
        ),
        migrations.DeleteModel(
            name='severidad',
        ),
        migrations.DeleteModel(
            name='tipoincidente',
        ),
        migrations.DeleteModel(
            name='ubicacion',
        ),
        migrations.DeleteModel(
            name='urgencia',
        ),
        migrations.AlterModelOptions(
            name='activos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ambientes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comentarios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='criticidadesservicios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='detallesambientes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='detallesservicios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='detallesubicacion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='documentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='estados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='etapas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='impactos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='incidentes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='origenes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='severidades',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposincidentes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ubicaciones',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='urgencias',
            options={'managed': True},
        ),
    ]
