# Generated by Django 3.1.7 on 2021-09-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0003_auto_20210409_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSeveridades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentesActivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Multicheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(max_length=45)),
                ('ubicacion', models.CharField(max_length=45)),
                ('servicio', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ambientes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comentarios',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='criticidadesservicios',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detallesambientes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detallesservicios',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detallesubicacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='documentos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estados',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='etapas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='impactos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='incidentes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='origenes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='severidades',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tiposincidentes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ubicaciones',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='urgencias',
            options={'managed': False},
        ),
    ]
